### ISSUE TITLE
depress the verbose of grid.latex

### ISSUE THREAD

**Issue by kongdd** [pmur002/dvir#4]
Dear @pmur002 , 

Do you have idea how to close the verbose of `grid.latex`?
![image](https://user-images.githubusercontent.com/9815742/180376100-6169d208-658b-418e-b1a8-a094e81a0eed.png)

Thanks very much!
Dongdong

**Comment by pmur002** [comment]
I have pushed a change (version 0.3-3) that turns the output off by default.  You can turn it back on with `grid.latex(..., quiet=FALSE)`

Does that do what you want ?

**Comment by kongdd** [comment]
Yes, it is. Thank you very much!
